spring:
  application:
    name: webpos-orders
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://172.24.0.207:3306/webpos
    url: jdbc:mysql://localhost:3306/webpos
    username: root
    password: root

webpos:
  db:
    database: webpos
    host: root
    pw: root
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 10

#mybatis:
#  table:
#    #create系统启动后，会将所有的表删除掉，然后根据model中配置的结构重新建表，该操作会破坏原有数据;
#    #update系统会自动判断哪些表是新建的．哪些字段要修改类型等，哪些字段要删除，哪些字段要新增，该操作不会破坏原有数据;
#    #add新增表/新增字段/新增索引新增唯一约束的功能，不做做修改和删除(只在版本1.0.9.RELEASE及以上支持);
#    #none系统不做任何处理;
#    auto: create
#  model:
#    #扫描用于创建表的对象的包名
#    pack: com.micropos.user.model
#  database:
#    #数据库类型目前只支持mysql
#    type: mysql
#
#mybatis-plus:
#  #固定的
#  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml