#eureka:
#  client:  # Not a client, don't register with yourself
#    registerWithEureka: false
#    fetchRegistry: false
#
#server:
#  port: 8761   # HTTP (Tomcat) port
#
#spring:
#  thymeleaf:
#    enabled: false     # Disable Thymeleaf
#  datasource:
#    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
eureka:
  client:  # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 8761   # HTTP (Tomcat) port

spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource